---

- name: Deploy jenkins
  docker_container:
    name: jenkins
    image: "{{ jenkins_image }}:{{ jenkins_image_tag }}"
    ports:
      - "0.0.0.0:50000:50000"
      - "0.0.0.0:18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/jenkins_home:/var/jenkins_home:rw
    state: started
    restart_policy: always
    env:
      VIRTUAL_HOST: "{{ jenkins_virtual_host }}"
      VIRTUAL_PORT: "8080"