jobs:
  - script: >
      pipelineJob('kayobe-service-reconfigure') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/Wasaac/a-universe-from-nothing')
                }
                branch('*/monasca-stein-dockerise')
              }
            }
            lightweight()
          }
        }
      }
