{% macro generate_job(name, cmd) %}
  - script: >
     pipelineJob('{{ name }}') {
        definition {
          cps {
            script("""\
              pipeline {
                options { disableConcurrentBuilds() }
                agent any
                stages {
                    stage ("Run command") {
                        steps {
                            build job: 'kayobe-command-run', parameters: [credentials(description: 'Kayobe SSH Key', name: 'KAYOBE_SSH_CREDS', value: 'kayobe-ssh-private-key'), credentials(description: 'Kayobe Ansible Vault Password', name: 'KAYOBE_VAULT_PASSWORD', value: 'kayobe-vault-password'), string(name: 'DOCKER_REGISTRY', value: 'http://localhost:4000/'), string(name: 'COMMAND', value: '{{ cmd }}'), credentials(description: 'Kayobe SSH Config file', name: 'KAYOBE_SSH_CONFIG', value: '')]
                        }
                    }
                  }
              }""".stripIndent())
          }
        }
      }
{% endmacro %}
jobs:
  - script: >
      pipelineJob('kayobe-command-run') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('{{ config_as_code_kayobe_config_repo }}')
                }
                branch('*/{{ config_as_code_kayobe_config_branch }}')
              }
            }
            lightweight()
          }
        }
      }
{{ generate_job('kayobe-overcloud-service-reconfigure', 'kayobe overcloud service reconfigure') }}
{{ generate_job('kayobe-network-connectivity-check', 'kayobe network connectivity check') }}
