{% macro generate_job(name, cmd) %}
  - script: >
     pipelineJob('{{ name }}') {
        definition {
          cps {
            script('''\
              pipeline {
                options { disableConcurrentBuilds() }
                agent any
                parameters {
                  string(defaultValue: "{{ config_as_code_kayobe_config_branches[0] }}", description: "Branch of kayobe config repository to use", name: "branch")
                }
                stages {
                    stage ("Run command") {
                        steps {
                            build job: "kayobe-command-run/${java.net.URLEncoder.encode(params.branch, 'UTF-8')}", parameters: [credentials(description: "Kayobe SSH Key", name: "KAYOBE_SSH_CREDS", value: "kayobe-ssh-private-key"), credentials(description: "Kayobe Ansible Vault Password", name: "KAYOBE_VAULT_PASSWORD", value: "kayobe-vault-password"), string(name: "DOCKER_REGISTRY", value: "{{ docker_proto }}://{{ docker_registry }}"), string(name: "COMMAND", value: "{{ cmd }}), credentials(description: "Kayobe SSH Config file", name: "KAYOBE_SSH_CONFIG", value: "")]
                        }
                    }
                  }
              }'''.stripIndent())
          }
        }
      }
{% endmacro %}
jobs:
  - script: >
      multibranchPipelineJob('kayobe-command-run') {
        branchSources {
          git {
            id('kayobe-config')
            remote('{{ config_as_code_kayobe_config_repo }}')
            includes('{{ config_as_code_kayobe_config_branches | join("") }}')
          }
        }
      }
# These don't work as the ${java.net.URLEncoder.encode( is getting intrepretted on load
# generate_job('kayobe-overcloud-service-reconfigure', 'kayobe overcloud service reconfigure')
# generate_job('kayobe-network-connectivity-check', 'kayobe network connectivity check')
{% if config_as_code_feature_tempest_enabled | default(false) %}
  - script: >
      pipelineJob('tempest') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('{{ config_as_code_tempest_repo }}')
                }
                branch('*/{{ config_as_code_tempest_branch | default("master") }}')
              }
            }
            scriptPath('{{ config_as_code_tempest_jenkinsfile | default("Jenkinsfile") }}')
            lightweight()
          }
        }
      }
{% endif %}